---
title: "Projects"
author: "Nathan Angell"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary

Hello my name is Nathan Angell and I am a senior at Bryant University. For the past 3 and a half years I have been a data scientist working on many different projects. These projects have been through school, internships, and personal projects. Here is a highlight of most of the projects I did to showcase my skills I have learned these past couple of years. 

# Personal Projects

#### 1: Research Intern - Direct Study: Application of Deep Learning


#### 2: Computational Biologist


# Classes

#### 1: Introduction to Programming (ISA 221)

- During my freshman year, I took my first programming course. I started off with no knowledge on how to code in python, and after a few weeks of work, I eventually worked my way up to this simple [program](ISA_221 start program.html). This program is able to take a list of 20 numbers and find the min, max, total, and average. 
  - [Program](ISA_221 start program.html)

- By the time the course was almost over, we eventually created a program that was able to calculate invoices for an employee working for a company. This program was very invaluable because it taught me the basics of object originated programming and most importantly, even a simple program like this one can still be pretty complex to create. The program is broken up into four different files. 
  - The [Program 6](Program 6.html) file is the head node of how the program runs. This program then calls [Program 5a](program5a.html) and [Program 5](program5.html) for important functions for Program 6 to run. Finally, both of those programs call [Module 4](Module4.html) for more important functions to for those programs to run. 
- [Program 6](Program 6.html)
- [Program 5a](program5a.html)
- [Program 5](program5.html)
- [Module 4](Module4.html)

#### 2: Database Management Systems Principles (ISA 341)

- My next programming class was called Database Management Systems Principles. This class is designed for students to teach them about MySQL and most importantly how relational databases work. 

- It first started off with how databases work and the different types of database designs that have been created over the past few years. We then moved over to MySQL, the most popular database query language in the world.

- On the topic of MySQL, the initial start was to created basic MySQL queries, [First SQL Assignment](Assignment_1.pdf) and as the class progressed we transitioned to more complex SQL statements, [Final SQL Assignment](Assignment_6.pdf).
  - The biggest difference between the first assignment we did to the second one, was the amount of data that was provided to us. For our first assignment we actually created small databases to perform basic SQL commands. As an example, highlighting a specific column or adding a column's values up. 
    - As we began working on the last assignment, we were grabbing data from a large CSV file and querying that data to our final results that you see on the bottom of every answer. These queries helped me navigate the SQL environment and most importantly provide me a foundation to understand additional sophisticated SQL queries. 
- [First SQL Assignment](Assignment_1.pdf)
- [Final SQL Assignment](Assignment_6.pdf)


#### 3: Data Visualization (ISA 310)
- First semester junior year, I took my first visualization course. This course taught me the importance of creating effective and simple graphs. Graphs are the **most** important tool to convey to your audience what information you are trying to present.
- We looked at all different kinds of graphs to understand their advantages and disadvantages, how can we make these graphs stand out, and the tricks to programmatically add additional features.
- This eventually led to our [final project](final_project.html) that encompassed all the teachings we learned throughout the semester. The data that I grabbed to make these plots were a little tricky, so I had to do some data engineering to fix it. 
  - I then proceeded to make a decision tree to predict the amount of days a patient would stay in the hospital based upon which hospital you were staying at, the severity of the illness, which department you are going to, etc. 
  - Next I created a graphically friendly bar chart to showcase the total admission deposits for each hospital. 
  - Then a detailed pie chart to break a part the length of stays for all the patients.
  - A stacked bar chart to showcase how many visitors a hospital patient will receive based upon their length of stay.
  - A stacked area chart to showcase which department was the most visited.
  - Finally, a line graph that presented which days, January 1st 2008 to December 31st 2009, the hospital received the most amount of revenue.
  
- [Final Project](final_project.html)
  
#### 4: Introduction to Machine Learning (ISA 340)

- For this class, my goal was to understand the different machine learning algorithms that are presently used in industry. Many companies use machine learning algorithms to predict what their customer might do next or something like computer vision. 
- During the start of the class, it was difficult for me to understand the material. I had to constantly read over the material and talk to my colleagues in class to get a better grasp upon it. Fortunately, as the class progressed, my hard work and dedication started to pay off because the material was getting easier to understand. 
- Our final project was to combine everything we have learned into one big project. This project entailed to do a lot of data engineering, that was almost 80% of our work, and the rest of the time was implementing our final models to our cleaned dataset.
- This [attachment](Final_Models.html) showcases all the models
- This [attachment](Final_EDA.html) showcases our data engineering
